Ready to review
MaxHlystov/AndroidNews pull request #2
Opened 2018-10-07 21:57 UTC by MaxHlystov

Ready to review

2018-10-10 11:07 UTC, zvezd04et commented on app/build.gradle
> +    implementation 'com.android.support:appcompat-v7:27.1.1'
Не знаю насколько обязательно, но все вроде перешли на androidX. Решил не переходить?

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +    private static final String simpleString = "0123456789";
Константы и поля обычно размещают в начале класса

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
Нужно еще было сделать для планшета две колонки

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        return getResources().getConfiguration().orientation;
Пусть Паша прокомментирует, но очень сложно читать код. Метод вычисляется в одной строчке, мне кажется, если эту строчке вызвать в методе getLayoutManager и не передавать в него параметр, то количество строк кода точно сократится.

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +                    Picasso.get().load(article.getUrlToImage()).into(image);
А чем Picasso лучше Glide? И по идее можно сохранить результат Picasso.get() в поле адаптера, то он не будет каждый раз вызываться, когда байндится вью

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/IDateConverter.java
> +    @NotNull String convert(@Nullable Date date);
К Паше вопрос: насколько распространенная практика создавать интерфейсы под служебные классы?

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +        return dateFormat.format(date);
Вот нутром чую, что менторы выложат какое-то простое решение в две строчки =)

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +    public void writeToParcel(@NonNull Parcel dest, int flags) {
Вот это круто, что сделал Parcelable! Я тоже думал, но поленился

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +    private final Source source;
В принципе стиль выдержан, что все внизу. Но как-то непривычно.

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/res/layout/activity_news_detailes.xml
> +        android:layout_width="match_parent"
Не нашел CollapsingToolbarLayout, так и не затащил?

2018-10-10 11:07 UTC, zvezd04et commented on app/src/main/res/layout/news_item_even_layout.xml
> +    android:background="#CCCCCCCC">
нет CardView

2018-10-10 12:22 UTC, MaxHlystov commented on app/build.gradle
> +    implementation 'com.android.support:appcompat-v7:27.1.1'
Да. Не в этой домашке.

2018-10-10 12:23 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +    private static final String simpleString = "0123456789";
Хрен его знает. Теоретически - это самая бесполезная внешнему пользователю информация. Инкапсуляция же.

2018-10-10 12:32 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +                    Picasso.get().load(article.getUrlToImage()).into(image);
Спрашивал на лекции у Сергея Рябова (который лектор). Он сказал, что Glide обладает большими возможностями. Если нужно просто картинку затащить, то Picasso - самое то. Эти штуки сами организуют кэш картинок, насколько я знаю, поэтому их можно не сохранять у себя.

2018-10-10 12:34 UTC, MaxHlystov commented on app/src/main/res/layout/activity_news_detailes.xml
> +        android:layout_width="match_parent"
Не, поленился :)

2018-10-11 18:35 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +    public void writeToParcel(@NonNull Parcel dest, int flags) {
Есть сайт, который это делает за тебя http://www.parcelabler.com/

2018-10-11 18:35 UTC, MaxHlystov commented on app/src/main/res/layout/news_item_even_layout.xml
> +    android:background="#CCCCCCCC">
Добавил :)

2018-10-11 21:06 UTC, zvezd04et commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +    private static final String simpleString = "0123456789";
Код больше приходится читать, чем писать. И поэтому лучше придерживаться общих правил.

2018-10-16 20:24 UTC, PStrelchenko requested changes
Реквестирую ченджи

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +    public static void startActivity(@NonNull Activity parent, @NonNull Article article) {
Если хочешь, чтобы этот метод работал не только в случае `Activity`, но и, например, с `deep link` - нужно вместо `Activity parent` использовать `Context parent`.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +            String content = inflateContent(article.getContent(), 4500);
Поясни, зачем ограничивать длину содержимого статьи? o_O
Откуда взялось число 4500 ?

2018-10-16 20:24 UTC, PStrelchenko commented on .gitignore
> +/.idea/libraries
Если есть строчка `.idea` -- другие строчки с этой папкой уже не нужны

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/AboutActivity.java
> +    public static void startActivity(@NonNull Activity parent) {
Можно подставить вместо `Activity parent` - `Context context` --> тогда твою activity можно будет открыть и из deepLink-ов, например

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +        return dateFormat.format(date);
Вооооу, действительно, тут какое-то слишком сложное решение. 
`android.text.format.DateUtils.getRelativeDateTimeString()` -- тебе поможет. Но круто, конечно, что сам написал.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +    public @Nullable
Отформатируй код.
Обычно аннотации помещают над методом, а модификаторы доступа - на одной строчке с типом:

```
@Nullable
public String getUrlToImage() {
    return urlToImage;
}
```

З.Ы. `urlToImage` - какое-то сложное, не совсем английское название переменной =) Я бы переназвал `imageUrl` - но это уже не относится к делу. Главное - отформатируй.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +    public static final Parcelable.Creator<Article> CREATOR = new Parcelable.Creator<Article>() {
Статические поля обычно помещают над всеми остальными

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Source.java
> +    public static final Creator<Source> CREATOR = new Creator<Source>() {
статические поля класса обычно помещают выше других полей.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/thirdpartyintentutils/BrowserIntent.java
> +public class BrowserIntent {
1. Название класса очень путает - BrowserIntent -- и ты думаешь, что это именно `Intent`, пока не заглянешь внутрь и не обнаружишь, что это `BrowserIntentProvider` =)

2. Мне кажется, я уже отмечал вопрос, "зачем было делать разные утилитные классы для Third-Party Intent-ов?" 
Ну то есть - у тебя есть набор функций, которые делают приблизительно одно и то же - создают intent-ы для посторонних приложений. Почему бы их не запихнуть в одно место-то? Самому же проще станет.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/thirdpartyintentutils/MailIntent.java
> +public class MailIntent {
Аналогичное замечание, как и в `BrowserIntent`.
Почему бы не создать один-единсвтенный класс `ThirdPartyIntentUtils`, куда поместить функции:
а) создания intent-а для browser-а
б) создание intent-а для mail-а

?

2018-10-16 20:24 UTC, PStrelchenko commented on imagedlistitem/src/main/java/ru/fmtkl/hlystov/imagedlistitem/ImagedTextView.java
> +        if (android.text.TextUtils.isEmpty(text)) {
Думаю тут не нужно указание пакета

2018-10-16 20:24 UTC, PStrelchenko commented on imagedlistitem/src/main/res/layout/main_layout.xml
> +        android:contentDescription="@string/item_image_description" />
`ctrl + alt + L`  - волшебная комбинация, которая тебе отсортирует все атрибуты

2018-10-16 20:24 UTC, PStrelchenko commented on imagedlistitem/src/main/res/layout/main_layout.xml
> +        tools:layout_height="@dimen/key_icon_size"
Если тебе нужен dimen только для tools - его не надо заводить вообще.
Ты мог просто здесь написать `tools:layout_height=24dp`.

2018-10-16 20:24 UTC, PStrelchenko commented on imagedlistitem/src/main/res/values/dimens.xml
> +    <dimen name="key_icon_size">24dp</dimen>
Не увидел использования вне tools

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +    private RecyclerView.LayoutManager getLayoutManager(int orientation) {
Аннотация `@NotNull` незаслуженно забыта =)

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +            Snackbar.make(recyclerView, "dfg", Snackbar.LENGTH_LONG).show();
что еще за `dfg`? =) Нужно нормальное сообщение об ошибке.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +    private void setNewsAdapter(List<Article> articlesList) {
аннотация `@Nullable` для параметра

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
Здесь можно было бы всегда возвращать только gridlayoutmanager, просто в зависимости от ориентации скармливать ему разное число колонок

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +    private void onNewsItemClickHandler(@NonNull View view, @NonNull Article article) {
а где используется параметр `view`?

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        return getResources().getConfiguration().orientation;
Можно вообще было бы написать метод "isHorizontalOrientation` или `isVertical` -- был бы аккуратный метод, который можно было бы легко использовать

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        SharedPreferences shp = getSharedPreferences(ALTERNATIVE_CONFIG, Context.MODE_PRIVATE);
Я бы вынес работу с SharedPrefs в другой класс - здесь это захламляет логику.
Сделай класс какой-нить, типо `NewsRepository`.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        ProgressBar progressBar = findViewById(R.id.activity_news_list__progress_bar);
вынеси progressbar в отдельное поле и получай ссылку в onCreate -> так отделишь немного код по смыслу. А то функция называется `updateNews`, а делает еще и показ/скрытие progressbar-а.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            this::onNewsItemClickHandler));
лучше переименуй функцию в `onNewsItemClicked`

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            this::onNewsItemClickHandler));
слово `Handler` дает путаницу с настоящим `Handler`-ом

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        return position & 1;
о_О

Я понимаю, что это учебный пример, но лучше так, все-таки, не делать. Обычно здесь берут элемент списка на позиции `position`, и смотрят на его свойства. и уже в зависимости от них - возвращают какой-то тип. 
Лайфхак - тут ты можешь возвращать в качестве viewType какой-нить `layoutId`-например, `R.layout.my_first_recycler_view_item`.
Тогда в функции onCreateViewHolder можно будет в качестве layoutId подставлять `viewType`.

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        @Nullable
Думаю, тут можно обойтись без `@Nullable` --> обычно ставят `NonNull` здесь. И тогда не нужно будет проверять, что поле не null

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                AboutActivity.startActivity(this);
Я бы выделял обработку кликов на элементы меню в отдельные функции --
```
case R.id.main_menu__about_item:
    onMainMenuAboutItemClicked();
    break;

case R.id.main_menu__get_online_news:
    onMainMenuGetOnlineNewsItemClicked();
    break;
```

Зачем - в будущем будет проще скопировать в `Presenter` ;)

2018-10-16 20:24 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +            case R.id.main_menu__get_online_news:
Именуй id-шники однообразно - у тебя выше `about_item`, пусть и здесь будет `get_online_news_item`. Мне кажется так понятнее будет.

2018-10-16 20:34 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +            Snackbar.make(recyclerView, "dfg", Snackbar.LENGTH_LONG).show();
Упс.

2018-10-18 09:42 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +            String content = inflateContent(article.getContent(), 4500);
Тот веб-сервис который я использовал, присылает обрезанную статью. Поэтому, эмпирическим путем, я подобрал оптимальный размер статьи, чтобы она не влезала на экран, но не скроллилась долго. Выносить в константы не хочу, т.к. это временное решение, я  буду заменять поставщика новостей (по крайней мере надеюсь это сделать) в пятой домашке.

2018-10-18 09:53 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +    public @Nullable
urlToImage - это поле JSON объекта.

2018-10-18 09:58 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +    public static final Parcelable.Creator<Article> CREATOR = new Parcelable.Creator<Article>() {
Я понимаю, порядок... Но, блин, реализация интерфейса Parcelable - это же частности жизни класса, фактически - это нарушение принципа единственной ответственности. Тут, фактически, нужно на уровне приложения делать локальную БД, которая будет по id раздавать объекты. Тогда никаких парселов не потребуется.

2018-10-18 10:05 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/thirdpartyintentutils/BrowserIntent.java
> +public class BrowserIntent {
Проще все в глобальную область видимость поместить. Как подсказывает опыт, лучше разделить, чем смешать.

2018-10-18 10:14 UTC, MaxHlystov commented on imagedlistitem/src/main/res/layout/main_layout.xml
> +        android:contentDescription="@string/item_image_description" />
Странно. Пишет, что ничего не поменял.

2018-10-18 10:17 UTC, MaxHlystov commented on imagedlistitem/src/main/res/values/dimens.xml
> +    <dimen name="key_icon_size">24dp</dimen>
Какое-то на меня помутнение нашло. Не помню почему так сделал. Установил реальные размеры из dimen.

2018-10-18 10:24 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +    private void onNewsItemClickHandler(@NonNull View view, @NonNull Article article) {
В объявлении интерфейса. Подразумевается, что событие onClick может прилетать от разных элементов управления. От каких и позволяет различить этот параметр. Сейчас в коде не используется. Потом будет.

2018-10-18 10:26 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        SharedPreferences shp = getSharedPreferences(ALTERNATIVE_CONFIG, Context.MODE_PRIVATE);
Ок.

2018-10-18 14:13 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            this::onNewsItemClickHandler));
onNewsItemClicked - это событие, а не обработчик.

2018-10-18 14:59 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        @Nullable
Поля из Article прилетают @Nullable.

2018-10-20 13:51 UTC, PStrelchenko requested changes
Нужны правки.

2018-10-20 13:51 UTC, PStrelchenko commented on app/build.gradle
> +    implementation "com.android.support:cardview-v7:$versions.supportLibs"
Просто будь внимательнее =)
ты в файле `dependencies.gradle` эту зависимость написал с ОДИНАРНЫМИ КАВЫЧКАМИ. А в них интерполяция не работает. 
Интерполяция - это когда ты пишешь внутри строчки какой-то вызов функции или еще что-то:
`"ololo_custom_text_then_$argument_or_another_${functionInvoke()}"`

2018-10-20 13:51 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +            String content = inflateContent(article.getContent(), 4500);
Подобные "магические числа" лучше как-то обзывать - поможет другим программистам понять тебя. Назови ее `TEMPORARY_MAX_ARTICLE_LENGTH` - хоть кусочек информации даст.

2018-10-20 13:51 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +                android.support.v7.app.ActionBar actionBar = getSupportActionBar();
Точно нужно указывать весь пакетный путь? Или достаточно `ActionBar` просто.

2018-10-20 13:51 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        @Nullable
Я имел в виду всякие `TextView`.

2018-10-20 13:51 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        @Nullable
Здесь тоже не очень-то и нужны `Nullable` аннотации над TextView.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +            return new ViewHolderEven(
Тут я в прошлый раз налажал с тем, что посоветовал метод `LayoutInflater.from` перенести в создание ViewHolder-а -- я потом посмотрел на свои проекты, сам же стараюсь делать так, чтобы у меня inflater создавался только один раз.
Так что - лучше все-таки вынести создание ViewHolder-ов в адаптер. 

ViewHolder как бы не должен понимать, как он создается. "Кто-то" (под "кто-то", разумеется, понимается адаптер) создает его, кто-то его застааляет биндить данные. Разделяем ответственность, так сказать.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +                    LayoutInflater.from(parent.getContext()).inflate(
Тут я в прошлый раз налажал с тем, что посоветовал метод LayoutInflater.from перенести в создание ViewHolder-а -- я потом посмотрел на свои проекты, сам же стараюсь делать так, чтобы у меня inflater создавался только один раз.
Так что - лучше все-таки вынести создание ViewHolder-ов в адаптер.

ViewHolder как бы не должен понимать, как он создается. "Кто-то" (под "кто-то", разумеется, понимается адаптер) создает его, кто-то его застааляет биндить данные. Разделяем ответственность, так сказать.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +        return dateFormat.format(date);
Можно посмотреть вот сюда - https://github.com/Android-Academy-MSK/NYTimes/commit/90df3638d23bd870dfbfebc4195373ad06e5e8c4

Здесь Сережа Рябов написал решение задачи форматирования даты. Может все-таки заюзать его? Ведь действительно в одну строку получится.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +public class NYTDateConverter implements IDateConverter {
У тебя этот класс, кстати, вообще не используется. Зачем он тогда?

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
Метод получения `currentLocale` я бы поместил в утилитный класс - `ContextUtils`. Мне кажется, там ему самое место.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +        is24HourFormat = android.text.format.DateFormat.is24HourFormat(context);
Здесь точно нужен путь со всеми пакетами? `DateFormat` с импортом не подходит разве?

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +        if (duration < 5L * 60L * 1000L) {
Если оставишь свою реализацию - проименуй константные значения. Ну то есть, понятно (более-менее, конечно), что здесь имелось в виду 5 минут, но если бы было написано `duration < FIVE_MINUTES_IN_MILLS` было бы понятнее.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +            return String.format(justNowFormat, timeString);
Для использования строчек с аргументами в Android можно использовать метод `context.getString(stringRes, arg1, arg2)` -тогда у тебя уйдет куча кода из конструктора. 

Да, ты можешь поспорить с этим пунктом =) Дескать, мы тогда будем вынуждены каждый раз дергать строчки из ресурсов, это может занимать лишние пару миллисекунд, но как бы, "преждевременные оптимизации - корень зла" (с) =) 
Мне кажется, не надо жертвовать читаемостью и понятностью кода до тех пор, пока вообще перед тобой не встанет проблема оптимизации.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +        } else if (duration < 24L * 60L * 60L * 1000L) {
Эти константы, кстати, можно получить вот так:

`TimeUnit.DAYS.toMillis(2L)`,
`TimeUnit.MINUTES.toMillis(5L)` -- это тоже чуток упростит код для понимания.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/STDDateConverter.java
> +                    0) // try FORMAT_ABBREV_RELATIVE
Что за константка `0`? У нее есть стандартное значение в `DateUtils`? Я такого не нашел =/ может тогда не надо использовать такой флаг?

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/appconfig/AppConfig.java
> +        SharedPreferences.Editor shp = context.getSharedPreferences(ALTERNATIVE_CONFIG,
1 - shared prefs нужно получать только один раз - в конструкторе, тогда не придется хранить контекст
2 - код можно написать в `flow` паттерне:

```
prefs.edit()
    .putBoolean(CONFIG_GET_ONLINE_NEWS, getOnlineNews)
    .apply();
```

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/appconfig/AppConfig.java
> +    private boolean getOnlineNews = true;
Не очень удачное название переменной для Java -> все-таки обычно префикс `get` имеют геттеры. Может назвать ее `needFetchNewsFromOnlineFlag`? Да, больше букв, но зато понятнее.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/appconfig/AppConfig.java
> +    private static final String ALTERNATIVE_CONFIG = "NewsListActivity_AltConfig";
Маленький совет по поводу именования констант в Android - я бы порекомендовал ввести для себя какой-то код-стайл, типа такого: 

```
Для констант, которые используются как ключи к SharedPreferences необходимо придерживатся следующих соглашений:

- Имя константы должно начинаться с префикса PREF_
- Значение константы должно формироваться по следующему правилу: {feature package name}.{flag}. Это необходимо, что бы ключи не пересекались, если используется один файл для SharedPreferences

const val PREF_IS_OAUTH_ENABLED = "ru.hh.network_source.is_oauth_enabled"

- Для констант, которые используются как тэг при логировании необходимо именовать константу LOG_TAG. Если названием для константы является название класса, и оно не помещается в 23 символа (ограничение LogCat-a), то можно удалить символы с конца строки.

private const val LOG_TAG = "InternetAvailabilityInt"

- Для констант, которые используются как тэг для экземпляра класса Fragment, стоит именовать тэг TAG и оставлять его с публичным доступом. Т.о. при добавлении экземпляра Fragment в FragmentManager можно будет использовать этот тэг.

- Константы, которые используются как значения ключей для объектов типа Bundle, должны иметь модификатор private и именоваться:

- с префиксом ARGS_, если объект используется для предачи параметров между компонентами приложения или при передачи аргументов в объект класса Fragment
- с префиксом STATE_, если объект используется для сохранения состояния экрана внутри метода onSaveInstanceState

- Константы, которые используются как аргумент requestCode в методе startActivityForResult, именуются с префиксом REQUEST_CODE_
```

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/appconfig/AppConfig.java
> +        SharedPreferences shp = context.getSharedPreferences(ALTERNATIVE_CONFIG, Context.MODE_PRIVATE);
Получать shared prefs стоит один раз, а потом уже использовать постоянно

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +public class Article implements Parcelable {
Согласись, что `Serializable` проще, ммм? =) Не пришлось бы писать (или генерировать) кучу кода.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on dependencies.gradle
> +        cardView      : 'com.android.support:cardview-v7:$versions.supportLibs',
не забываем `ctrl + alt + L` делать

2018-10-20 13:51 UTC, PStrelchenkoHH commented on imagedlistitem/build.gradle
> +    buildToolsVersion '28.0.3'
А разве здесь это нужно указывать вообще?

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            this::onNewsItemClickHandler));
Так в этом-то и суть. Что ты от `View` прокидываешь какое-то событие в компонент, который занимается обработкой кликов, обработкой какой-то бизнес-логики. 
Можешь оставить и так.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +        NewsGetter newsGetter = new NewsGetter(getString(R.string.country_code), configuration.isGetOnlineNews());
Это похоже на кусок домашки № 4. Но ты еще делаешь ДЗ № 3. 
Не надо смешивать ДЗ-хи, пожалуйста, реально очень тяжело читать все это скопом. 

Почему не ревьювю по отдельным коммитам - потому что я буду тогда делать какие-то замечания, а они, возможно, уже пофикшены в будущих коммитах. И плюс, мне хочется видеть картину целиком, а не фрагментарно. Если я захочу понять процесс твоего мышления - тогда да, я буду смотреть на отдельные коммиты.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +    private int getOrientation() {
Зачем этот отдельный метод? Я к тому, что обычно тебе ориентация нужна только чтобы проверить, какая она - вертикальная или горизонтальная.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +    protected abstract static class ViewHolder extends RecyclerView.ViewHolder {
Не надо так переусложнять - никто подобные абстракции не делает. Обычно, если у тебя реально сложное приложение и списки, нужно испольовать просто `DelegateAdapter`. А в данном учебном примере - это просто какой-то overhead.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        protected final TextView source;
Зачем тут `protected` поля? Классы `ViewHolder`–ы обычно не наследуют друг от друга - один ViewHolder используется в одном DelegateManager, поэтому в этом просто нет никакой необходимости.
Пока ты один пишешь проект, ты, предположим, это понимаешь, и не будешь наследовать свой ViewHolder, но придет кто-то еще и он обязательно сотворит какую-нибудь дичь с этим.

2018-10-20 13:51 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +public class Article implements Parcelable {
Судя по всему, этот класс у тебя - это network модель. На это указывает, что ты все поля поставил `Nullable`. Ты получаешь их по сети.
Чтобы просто упростить себе жизнь, я бы сделал новую модель - ArticleDomain, которая бы использовалась в приложении, и имела бы все поля `NonNull`. Я бы использовал эту модель повсюду, и мне бы не пришлось писать кучу `if`-ов, проверяющих что-то на null. 
В больших приложеньках так и делают.

2018-10-20 22:44 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            this::onNewsItemClickHandler));
this::onNewsItemClickHandler - это реакция на событие onNewsItemClick

2018-10-20 23:03 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +            return new ViewHolderEven(
Третья лекция слайд 188 - best practice: 
 public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
    return ViewHolder.create(parent);
  }

2018-10-20 23:04 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +public class NYTDateConverter implements IDateConverter {
Жалко удалять :)

2018-10-20 23:24 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +            return String.format(justNowFormat, timeString);
Мне тогда придется хранить контекст. Не хочу с контекстом связываться в утилитном классе.

2018-10-20 23:53 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +    private int getOrientation() {
В подсказке к "Configuration.ORIENTATION_" насчитал четыре варианта константы. Поэтому отдельный метод.

2018-10-20 23:55 UTC, MaxHlystov commented on imagedlistitem/build.gradle
> +    buildToolsVersion '28.0.3'
Пока еще с gradle не разбирался.

2018-10-21 00:01 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +    protected abstract static class ViewHolder extends RecyclerView.ViewHolder {
Изобретение велосипедов как часть учебного процесса :)

2018-10-24 18:52 UTC, PStrelchenko requested changes
Реквестирую ченджи =)

2018-10-24 18:52 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsDetailesActivity.java
> +            final int TEMPORARY_MAX_ARTICLE_LENGTH = 4500;
Я имел в виду `private static final` константу =)

2018-10-24 18:52 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            this::onNewsItemClickHandler));
Спорить уже не буду, но просто, с точки зрения английского языка, ты написал - "на обработчике клика на новость". 
Хочешь оставить слово `handler` - велкам =) Но коллеги могут не понять. Можно заменить твое название на `handleOnNewsItemClick` - получится "обработать нажатие на новость".

2018-10-24 18:52 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        return position & 1;
Я, единственное, надеюсь, что в реальных приложениях так не будешь писать. Просто потому что это, внимание, **непонятно** =)
Гораздо понятнее было бы, если бы ты написал, например, во так:

```
int viewType;
if (position % 2 == 0) {
    return EVEN_POSITION_VIEW_TYPE;
} else {
    return ODD_POSITION_VIEW_TYPE;
}
```

2018-10-24 18:52 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +            return new ViewHolderEven(
Учитывая, что ты не делаешь в этом статическом методе ничего кроме inflate-а нужного layout-а, ты не получаешь никакого профита от того, что ты так написал.
Профитом было бы, например, установка clickListener-ов.

2018-10-24 18:52 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/NYTDateConverter.java
> +public class NYTDateConverter implements IDateConverter {
Не надо оставлять мертвый код. Ты же уже решил, что не будешь этим классом пользоваться - это не задел на будущее.

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/thirdpartyintentutils/IntentUtils.java
> +    public static void showIntent(@NonNull Activity activity,
Здесь тоже можно заменить на Context

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsResponse.java
> +    private final String status;
Добавь аннотации `@SerializedName("<имя твоего поля>")`

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static final String formatNewsURL = "https://newsapi.org/v2/top-headlines?country=%s&apiKey=%s";
Имя констант обычно пишут в SCREAMING_SNAKE_CASE

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static final String formatNewsURL = "https://newsapi.org/v2/top-headlines?country=%s&apiKey=%s";
Статические поля перенеси повыше обычных

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +            Log.d("NewsApp", "Error", ex);
Добавь emitter.onError сюда

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +        emitter.onNext("{\"status\":\"ok\",\"totalResults\":20,\"articles\":[{\"source\":{\"id\":\"rbc\",\"name\":\"RBC\"},\"author\":null,\"title\":\"Росморпорт прокомментировал информацию о взрыве
Давай эту длинную простыню JSON-а перенесем в файлик отдельный в asset-ах, и оттуда уже прочитаем

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +                .map((String it) -> new Gson().fromJson(it, NewsResponse.class))
У тебя на каждый map создается отдельный Gson-объект - не надо так =)

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +        Observable<NewsResponse> obs = Observable.create((ObservableEmitter<String> it) -> {
Замени здесь Observable на `Single` - он специально предназначен для эмитинга одного элемента.

2018-10-24 18:52 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +                emitter.onNext(s);
Или здесь не забудь `emitter.onComplete()`.

2018-10-29 06:32 UTC, PStrelchenko approved these changes
Продолжаем работу над другими ДЗ

2018-10-29 06:32 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/appconfig/AppConfig.java
> +    private static final String PREF_NEED_FETCH_NEWS_FROM_ONLINE_FLAG =
= PREF_ALTERNATIVE_CONFIG + ".need_fetch_news_from_online_flag"; 

Чтобы не ошибиться при написании пути к новому флагу

2018-10-29 08:06 UTC, merged