Feature/ex 4
MaxHlystov/AndroidNews pull request #3
Opened 2018-11-02 18:45 UTC by MaxHlystov

2018-11-03 12:01 UTC, PStrelchenko requested changes
Нужны доработки

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/NewsApplication.java
> +            Log.e(LOG_TAG, "Global error handler", e);
Можно, конечно, и так. Но я бы взял нормальный error handler, который предлагался в статье. Он рассматривает разные ситуации, а не просто все сапрессит

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/NewsApplication.java
> +            Log.e(LOG_TAG, "Global error handler", e);
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                Log.e(NewsApplication.LOG_TAG, String.format("Unexpected option: %s", item.getTitle()));
Можно, конечно, использовать тэг приложения. Но представь, если у тебя будет штук 20 экранов, и на каждом будет подобный текст "Unexpected option: %s"? (а такое может быть, уж поверь =)) -- как ты поймешь, на каком экране случилась ошибка?
Тогда-то и пригождается отдельный тэг на каждый экран

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            hideProgress();
Давай допишем код, чтобы показывался error stub с текстом ошибки и кнопкой `retry` в случае какой-то ошибки. Кнопка должна запустить запрос заново. Это будет и правильно, с точки зрения логики приложения, и доп.практика

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        DiffUtil.DiffResult diff = DiffUtil.calculateDiff(new DiffUtil.Callback() {
Вынеси реализацию callback-а в отдельный класс, чтоб не загромождать Recycler adapter

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +                        .resize(800, 600)
800 и 600 - это какие-то магические чиселки =) вынеси в константы

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/STDDateConverter.java
> +        if (context != null) {
Вопрос -- а Newsgetter не мог заняться еще дополнительно и конвертацией? 
А то эти танцы с WeakReference прям пугают чуток

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +        NewsGetter.countryCode = countryCode == null ? "us" : countryCode;
`us` - константа --> выносим в `private static final`.

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +        newsObserver = Single.create((SingleEmitter<String> singleEmitter) -> {
`Thread.sleep` можно убрать и добавить в цепочку оператор `delay`, который сделает тоже самое.

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
>          Gson gson = new Gson();
объект `gson`-а можно создать 1 раз в конструкторе `NewsGetter`

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
>      @NonNull
это контанта --> я говорил, что по java code convention, такие штуки оформляются в SCREAMING_SNAKE_CASE

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static void createOnlineRequest(@NonNull SingleEmitter<String> emitter) throws IOException {
Блин, это какой-то монстр =) 
Конечно, хорошо, что ты разобрался, как делать все эти запросы при помощи базовых классов, но давай для упрощения поддержки и твоего кода, перепилим все на Retrofit. И мне читать проще будет, и тебе уже пятую домашку почти не надо будет дорабатывать.

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static void getOfflineNews(@NonNull SingleEmitter<String> emitter, @NonNull Context context) {
https://stackoverflow.com/questions/9563373/the-reason-for-assets-and-raw-resources-in-android

Я когда рассказывал про asset-ы, совсем забыл про такую штуку, как res/raw ресурсы. 
В случае, когда тебе пофигу на иерархию файлов, ты можешь запихнуть подобные json-файлы в папку res/raw --> андроид тебе сгенерирует автоматически id-шник для этого ресурса, и до него можно будет достучаться через `R.raw.your_id`. Правда, обертку для получения текста придется все равно написать.

Итого:

1. Я бы вынес в `raw` этот файл, чтобы не хардкодить имя ресурса в константы
2. Сделал бы отдельным классом `RawResourceExtractor`, который по id ресурса мне достанет текст, содержащийся в нем. Так мы еще немного упростим наш класс-репозиторий.

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static void getOfflineNews(@NonNull SingleEmitter<String> emitter, @NonNull Context context) {
Ну, кстати, в отдельный класс получение ресурса ты и вынес - хвалю =) 
Только название метода почему-то с большой буквы у тебя - `ReadFromAssetsFile` -> поправь

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    public static Single<NewsResponse> getNewsObserver(@NonNull Context context,
Метод, имхо, выглядит реально страшно.
Мне кажется, его можно упростить, если разнести его обязанности по нескольким классам.

То, что ты написал - в смысле `NewsGetter` может быть "тупым репозиторием", который вне зависимости от каких-либо условий всегда отдает нам `Single`. Этот репозиторий будет отвечать только за получение данных и больше ничего. Тогда получится, что метод будет таким:

```
public final class NewsGetter {
    ...
    @NonNull
    public static Single<List<NewsItem>> getNewsObservable(
            @NonNull Context context,
            @Nullable String countryCode,
            boolean needFetchFromOnline
    ) {
        return Single.fromCallable(new Callable<List<NewsItem>>() {
            @Override
            public List<NewsItem> call() throws Exception {
                if (needFetchFromOnline) {
                    return getFromOnline();
                } else {
                    return getFromOffline()
                }
            }
        });
    }
```

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
>      @NonNull
Наверху еще есть `IDLE_TIME`

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
>      @NonNull
А ниже - `bufferSize`

2018-11-03 12:01 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    public static Single<NewsResponse> getNewsObserver(@NonNull Context context,
Во-вторых - давай мы избавим repository от обязанности хранить какие-то данные внутри себя. Пусть репозиторий станет объектом, который просто получает данные. А за хранение пусть отвечает что-то промежуточное между activity и этим репозиторием.
Так ты уберешь вот это условие

```
 if (newsObserver != null
                && NewsGetter.countryCode != null
                && NewsGetter.countryCode.equals(countryCode)
                && NewsGetter.online == online) {
            return newsObserver;
        }
```

И метод станет еще проще

2018-11-03 12:01 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static Single<NewsResponse> newsObserver = null;
Вообще, не очень понял, почему все переменные стали статическими =/
Чтобы запрос переживал переворот экрана?..
Так он не переживает, кстати. 

Проверял вот так:
1) включить режим don't keep activities
2) стартануть приложение
3) перевернуть экран несколько раз

Ожидал, что примерно через пять секунд после старта приложения у меня все-таки появятся данные. А здесь - после каждого переворота делается новый запрос. 

Надо допилить, чтобы запрос переживал пересоздание активити + результат сохранялся между переворотами экрана.
Можешь использовать что захочешь: Loaders, Moxy, ViewModel - лучше последние два.

2018-11-04 09:12 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                            hideProgress();
Это задача 5 домашки.

2018-11-04 09:14 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static void createOnlineRequest(@NonNull SingleEmitter<String> emitter) throws IOException {
Это задача пятой домашки.

2018-11-04 09:26 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/NewsApplication.java
> +            Log.e(LOG_TAG, "Global error handler", e);
done

2018-11-04 09:42 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsListActivity.java
> +                Log.e(NewsApplication.LOG_TAG, String.format("Unexpected option: %s", item.getTitle()));
done

2018-11-04 09:53 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        DiffUtil.DiffResult diff = DiffUtil.calculateDiff(new DiffUtil.Callback() {
done

2018-11-04 09:54 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +                        .resize(800, 600)
Я все это и многое другое в пятой домашке поправил.

2018-11-04 10:04 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +                        .resize(800, 600)
done

2018-11-04 10:09 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/fashionutils/STDDateConverter.java
> +        if (context != null) {
А как же принцип разделения отвественности?

2018-11-04 10:21 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +        NewsGetter.countryCode = countryCode == null ? "us" : countryCode;
done

2018-11-04 10:43 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +        newsObserver = Single.create((SingleEmitter<String> singleEmitter) -> {
done

2018-11-04 10:43 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
>          Gson gson = new Gson();
done

2018-11-04 10:44 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
>      @NonNull
done

2018-11-04 12:04 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static void getOfflineNews(@NonNull SingleEmitter<String> emitter, @NonNull Context context) {
done

2018-11-04 12:11 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    public static Single<NewsResponse> getNewsObserver(@NonNull Context context,
Не понял слово repository. Что ты имеешь ввиду?

2018-11-04 14:39 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    public static Single<NewsResponse> getNewsObserver(@NonNull Context context,
Навтыкал отладочной информации. Судя по логам, ты не прав. Активити дестроятся. Обсервер остается.

2018-11-04 15:13 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static Single<NewsResponse> newsObserver = null;
Навтыкал отладочной информации. Судя по логам, ты не прав. Активити дестроятся. Обсервер остается.

2018-11-05 20:20 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    private static Single<NewsResponse> newsObserver = null;
done

2018-11-05 20:20 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +    public static Single<NewsResponse> getNewsObserver(@NonNull Context context,
done

2018-11-11 12:36 UTC, PStrelchenko approved these changes
Большая часть моих замечаний относилась к пятой ДЗ. Поэтому апрувлю и смотрю пятую.

2018-11-26 11:14 UTC, merged