Feature/ex 5
MaxHlystov/AndroidNews pull request #4
Opened 2018-11-02 21:32 UTC by MaxHlystov

2018-11-11 18:07 UTC, PStrelchenko requested changes
Нужны доработки

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    public static final String DEFAULT_NEWS_SECTION = "home";
Лучше использовать enum.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    private String news_section;
Не java code style.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    private final WeakReference<SharedPreferences> sharedPreferencesWeakReference;
Здесь WeakReference не нужна. Пусть этот класс всегда хранит ссылку на SharedPreference-ы. Если ты получил sharedPref-ы из application context-а, то они никуда не утекут. Плюс, ты же не хранишь контекст здесь.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    public static final String DEFAULT_NEWS_SECTION = "home";
В pref-ах нужно будет хранить не enum.name, а какую-то константу, которая однозначно связана с enum-значением. Типо:

```
enum Section {
    HOME("home"),
    OPINION("opinion");

    @NonNull
    private final String networkPath;
}
```

--> в префы сохраняем `networkPath`, и enum-значение восстанавливаем по нему.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    public String getNews_section() {
не java code style

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYT_Retrofit_Endpoint.java
> +public interface NYT_Retrofit_Endpoint {
не java code style

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
Интерсептор для логов обычно добавляют только в DEBUG сборке. В релизной у тебя не должны никакие логи светиться в консоли.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +                .addInterceptor(new APIKeyInterceptor(BuildConfig.NYT_APIkey))
Не java code style

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +                .addInterceptor(logging)
LoggingInterceptor надо добавлять самым последним среди всех, чтобы он смог учесть какие-то другие изменения от других интерсепторов

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +    private static final int TIMEOUT_IN_SECONDS = 2;
Две секунды - это прям мало. Обычно здесь ставят минимум 10. Могут и больше, в зависимости от объема данных, которые кочуют туды-сюды

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +                    if (THROW_ERROR) throw new IOException("Test exception!");
Видимо какой-то код для тестов.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (dtoNewsResponse != null) {
Чтобы уменьшить вложенность кода - пойди от обратного.

```
if (dtoNewsResponse == null) {
    return new NewsResponse("Error", 0, null);
}

...

```

Читать проще будет

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +    public static Article convertToArticle(@NonNull DTOResult dtoResult) {
Класс называется NewsConverter, а внутри него есть метод для конвертации какого-то DTO в Article. Может это зона ответственности какого-то ArticleConverter?

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +    private static Source NYTSource;
Не java code style, переменная не должна начинаться с большой буквы. `nYTSource` выглядит не оч красиво, можно назвать `newYourkTimesSource`.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (NYTSource == null) NYTSource = new Source("NYT", "NYT");
Вопрос - что такое `Source`.
Он нигде не используется. В смысле, что внутри `Article` есть метод `getSource`, но его никто не использует.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (date == null) return null;
Фигурные скобки

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (multimedia != null) {
чтоб уменьшить вложенность - инвертируй условие.

```
if (multimedia == null) {
    return null;
}

for ...
```

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        return new NewsResponse("Error", 0, null);
"Error" - какая-то магическая константа, не очень понятная.

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +                   @Nullable String section,
Такие большие конструкторы обычно заменяют на Builder-паттерн

2018-11-11 18:07 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsSectionsSpinner.java
> +        if (currentPosition < 0 || currentPosition >= sections.length) return null;
фигурные скобки не зыбываем

2018-11-29 11:14 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    private String news_section;
Done

2018-11-29 11:29 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    private final WeakReference<SharedPreferences> sharedPreferencesWeakReference;
Done

2018-11-29 11:29 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    public String getNews_section() {
Done

2018-11-29 11:30 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYT_Retrofit_Endpoint.java
> +public interface NYT_Retrofit_Endpoint {
Done

2018-11-29 18:59 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    public static final String DEFAULT_NEWS_SECTION = "home";
Done

2018-11-29 18:59 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (date == null) return null;
Done

2018-11-29 19:24 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (multimedia != null) {
Мне кажется, что как сейчас - элегантнее. А по новому, придется null два раза возвращать.

2018-11-29 19:36 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        return new NewsResponse("Error", 0, null);
Удалил.

2018-11-29 19:49 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsSectionsSpinner.java
> +        if (currentPosition < 0 || currentPosition >= sections.length) return null;
done

2018-11-29 20:07 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +                .addInterceptor(logging)
Done

2018-11-29 20:08 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +    private static final int TIMEOUT_IN_SECONDS = 2;
Done

2018-11-29 20:29 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (NYTSource == null) NYTSource = new Source("NYT", "NYT");
Удалил.

2018-11-29 20:30 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +                .addInterceptor(new APIKeyInterceptor(BuildConfig.NYT_APIkey))
Тут не понял, что не так.

2018-11-29 20:30 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
Done

2018-11-29 20:32 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsGetter.java
> +                    if (THROW_ERROR) throw new IOException("Test exception!");
Завернул в условие.

2018-11-29 20:40 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (dtoNewsResponse != null) {
Done

2018-11-29 20:42 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +    public static Article convertToArticle(@NonNull DTOResult dtoResult) {
Не. Хотя бы здесь не будем объектный террор устраивать. Достаточно функции. Еще один объект-функция это для меня будет слишком. Сделал ее приватной.

2018-11-29 20:42 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +    private static Source NYTSource;
Удалил.

2018-11-29 21:25 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/Article.java
> +                   @Nullable String section,
Сделал, но не вижу методического смысла в дата-классе создавать билдер. Что он облегчил? Понимать, что происходит стало сложнее. Появилась возможность у того, кто будет читать код, подозревать, что Article, не такой простой класс, как кажется. Поддержка усложнилась, теперь нужно в двух местах править поля.

2018-11-29 21:36 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    public static final String DEFAULT_NEWS_SECTION = "home";
Отвратительно получилось. Крайне мне не нравится такое решение. Засунули в перечисление список элементов, который может динамически меняться в любой момент. Мы теперь будем перекомплировать программу под каждое изменение NYT-api. В случае если нам нужна бизнес-логика на разделах новостей, нужно опредмечивать те разделы, которые используем. Для текущей логики работы нам нужно два значения типа новостей: HOME - потому что он по умолчанию, и OTHER - все остальное. Если я захочу использовать спорт, то добавлю в перечилсение спорт. А не так, как сейчас.

2018-11-30 11:28 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +                .addInterceptor(new APIKeyInterceptor(BuildConfig.NYT_APIkey))
Done

2018-12-01 09:56 UTC, PStrelchenkoHH commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    public static final String DEFAULT_NEWS_SECTION = "home";
Насколько я знаю, только один вариант поможет не перекомпилировать каждый раз приложение для изменения списка категорий - remote config от Firebase.

2018-12-01 10:22 UTC, PStrelchenko requested changes
Ченджи

2018-12-01 10:22 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    private NewsSection news_section;
Не java code style. Здесь должно быть `newsSection`.

2018-12-01 10:22 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/NewsApplication.java
> +        RxJavaPlugins.setErrorHandler(e -> {
Я бы вынес в отдельный метод - `initRxJavaPlugins`

2018-12-01 10:22 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/NewsConverter.java
> +        if (multimedia != null) {
Ок

2018-12-01 10:22 UTC, PStrelchenko commented on app/src/main/AndroidManifest.xml
>              android:name=".NewsDetailesActivity"
Что будет при перевороте экрана? WebView не перезагружает контент?

2018-12-01 10:22 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        if (layoutId != R.layout.news_item_even_layout
У тебя были ситуации, когда `viewType` возвращал ненужный layoutId?

2018-12-01 10:22 UTC, PStrelchenko commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +        Retrofit retrofit = new Retrofit.Builder()
ой.  
Каждый раз заново создавать API интерфейс не надо.
Нужно 1 раз создать NYTRetrofitEndpoint, а потом его уже использовать.

2018-12-02 11:15 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/AppConfig.java
> +    private NewsSection news_section;
Done

2018-12-02 11:15 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/NewsApplication.java
> +        RxJavaPlugins.setErrorHandler(e -> {
Done

2018-12-02 11:39 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/androidnews/NewsRecyclerAdapter.java
> +        if (layoutId != R.layout.news_item_even_layout
Ага. Постоянно. Если в параметр можно передать, что-то не то. Это обязательно произойдет.

2018-12-02 11:58 UTC, MaxHlystov commented on app/src/main/java/ru/fmtk/khlystov/newsgetter/webapi/NYTNetworkAPI.java
> +        Retrofit retrofit = new Retrofit.Builder()
Done

2018-12-02 12:02 UTC, MaxHlystov commented on app/src/main/AndroidManifest.xml
>              android:name=".NewsDetailesActivity"
Перезагружает.

2018-12-02 20:33 UTC, MaxHlystov commented on app/src/main/AndroidManifest.xml
>              android:name=".NewsDetailesActivity"
Сделал чтобы webView восстанавливал данные при повороте экрана, а не загружал их из сети.

2018-12-08 11:46 UTC, PStrelchenko approved these changes
Поехали к следующей ДЗ

2018-12-10 21:57 UTC, merged